### ISSUE TITLE
Decoding from a Hyper stream?

### ISSUE THREAD

**Issue by thejefflarson** [alexcrichton/flate2-rs#35] opened 2016-01-05 19:15 UTC
I'm using flate2 to deflate some web crawl data via a hyper stream, and I think `GzReader` is quitting early. Here's my code:

https://gist.github.com/thejefflarson/e57cefd2eb09ec0c8dee

I'm new around these parts so I may be doing something wrong.

**Comment by alexcrichton** [comment] 2016-01-11 19:53
I think that this is actually a dupe of https://github.com/alexcrichton/flate2-rs/issues/23 where the underlying stream appears to be a concatenation of multiple gzip files. Thanks for the report though!

**Closed by alexcrichton** 2016-01-11 19:53 UTC

**Comment by thejefflarson** [comment] 2016-01-11 20:46
Oh I see, thanks for the pointer!
